language: node_js

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  local_dir: public
  repo: elepnt/elepnt.github.io
  target_branch: master
  email: deploy@travis-ci.org
  name: deployment-bot
